### ISSUE TITLE
WSL short lik not resolving properly

### ISSUE THREAD

**Issue by samirgunic** [MicrosoftDocs/WSL#181]
I have Windows 10 Pro version 1709 here, and I cannot access any of the distributions in the Microsoft Store app by using the short link you see below.

https://aka.ms/wslstore

If I open that link, it brings up the Microsoft Store, and a meaningless message you see below.

> Wait a while, then try that again. Something happened on our end.

<img width="955" alt="ms-store-wsl" src="https://user-images.githubusercontent.com/3742529/39691318-8bb2fd82-51dd-11e8-9f36-b93196f82ae5.png">

It doesn't offer any kind of help, and if I do a web search on that I find a Microsoft employee on the Answers/Community forum suggesting that people who encounter this particular message should try to perform a system file check, or reset the store cache. Why would I do that when it clearly says that the problem is on your end?

If I do a search for "Linux", "Ubuntu", "Canonical", I get no results.

> No results were found for Linux
> No results were found for Ubuntu
> No results were found for Canonical

But using the [direct links](https://docs.microsoft.com/en-us/windows/wsl/install-win10), I was able to get the right app page up on the Microsoft Store app by clicking on the "get the app" button on the web page that opens up in the web browser.

I have Windows Subsystem for Linux enabled in Windows Features, and I am not sitting behind a corporate firewall. It should work, just as easily as it did with the `lxrun` command in the old Windows 10 version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by Netoperz** [comment]
Same problem here, Yesterday i have downloaded iso of 10 from msdn and clean install, due to the hdd swap, and everything is fine, i have whole linuxsubsystem and stuff, but when i want to install any of the apps from windows store just i can see fast progress barr anothing happends

**Comment by Netoperz** [comment]
And also the same result from shortlink.
And this is not only linux related, i wanted to install whatsapp and the same, but updates were installed properly, so I think microsoft has blown up the windows store again. pitty that this happend always when i need it, so the solution that worked for me was installing debian /ubuntu  on hdd as a main system :) and it works ,

**Comment by samirgunic** [comment]
@Netoperz you could have used the direct links I mentioned above. If WSL is what you need, and you want the Ubuntu dist, then you can try the direct link below. For the next time that is.

https://www.microsoft.com/store/p/ubuntu/9nblggh4msv6

**Comment by Netoperz** [comment]
I wanted debian distro, and nowhere on internet :) i could find direct link for debian, 
It could be good thing to publish list of direct links in that kind of situations, especially that those functions like WSL is mainly used for people who really need those features to their work.
The bug was fixed with yesterdays windows update pushed to the devices, so now store works fine.

The only thing that still is messed up is time control, but it is not related to this repository/project (i have got problems with time, not sure what exactly causes that because i had no time for testing, but windows can change the system time by it self, and the correct time is shown when you turn off and back turn on automatic date and time settings. The CMOS battery is fine, main battery always fine, bios keeps proper date, and native ubuntu has no problems, so the problem is windows related. Showing over reboots.
I've noticed it on  Dell 7280 i7 6600 16GB ram DDR4 1TB NVME 960 EVO PRO, touch, LTE (so the machine is quite powerfull, battery time 12-21h so it is not related to the processing power/hardware resources or power source) If someone knows what might happend just send me a msg) 

On this topic You could publish direct link to the debian distro for future reference, and we may assume that this issue is closed, as update is fixing the store problem.

This build and version with curren update works fine:

![zrzut ekranu 2](https://user-images.githubusercontent.com/16330298/39956385-8904e6d0-55df-11e8-944d-0f7b13458f88.png)

**Comment by samirgunic** [comment]
@Netoperz thanks for the input! The issue I raised here is that the short URL for the WSL main page in the store did not resolve properly.

The link in question is:
https://aka.ms/wslstore

Can you please click on this link and tell me if you are able to see the WSL main page in the Windows/Microsoft Store?

**Comment by samirgunic** [comment]
So I took another look at this and I think I have found the cause of the problem. The short link `https://aka.ms/wslstore` redirects to `ms-windows-store://collection/?CollectionId=LinuxDistros` and the **Linux Distros** collection has been removed from Microsoft Store. So the solution is pretty simple. Just add the Linux Distros collection to the Store again and the short link will work. I don't know why someone would remove the Linux Distros collection, but that's what I am seeing here.

![wsl-collections-se](https://user-images.githubusercontent.com/3742529/39961295-2dd36210-5633-11e8-8738-a540cace306e.png)

Windows version 1803, build 17134.48
Microsoft Store version 11803.1001.9.0

**Comment by samirgunic** [comment]
Now I also know why the collection is not found. Apparently I live in the wrong country. As I suspected, by changing my location I can see a different set of collections in Microsoft Store. Following collections are missing when the location is set to Sweden.

- eBooks for grads
- Marvel 10th anniversary sale
- Hidden object games
- Unleash your creativity

But not if I set my location to United States.

![wsl-collections-en-us](https://user-images.githubusercontent.com/3742529/39961409-97e5b746-5635-11e8-8ee2-8c2ad7e257d7.png)

Note however that the Linux Distros collection is still missing. Or rather, it is hidden. Because I can now resolve the short link and ms-windows-store scheme for Linux Distros collection as you can see below.

**Input:**
`ms-windows-store://collection/?CollectionId=LinuxDistros`

**Output:**
![wsl-en-us](https://user-images.githubusercontent.com/3742529/39961431-2b4b12a6-5636-11e8-9448-93f97fb3ac33.png)

**Comment by samirgunic** [comment]
@Netoperz try changing your location from Poland to United States.

![region-settings](https://user-images.githubusercontent.com/3742529/39961516-0302d1ec-5638-11e8-8ef4-6a80701a1792.png)

Then use this link:
https://aka.ms/wslstore

It should work.

**Comment by Netoperz** [comment]
Strange, today the short-link is not working, my location is set to Poland, and i see the message "wait a moment and try again, the problem occurs on our side" (free translation from polish)in windows store.
So i can confirm, that shortlink is not acessable from polish location, windows build posted above. 

but when i put "debian" or "linux" in search box, the distros are there and install button installs them properly on system.

When i change the location to United States in System region settings as You have asked , i can see the whole collection.

So i can confirm the scenarios that You have tested are true.

So not working link is related to the country settings in windows.
Windows store is not letting people from other country than US to see the collection.

Hope it helps.

**Comment by Netoperz** [comment]
@samirgunic  could You test if You can install WhatsApp ?
https://www.microsoft.com/pl-pl/store/p/whatsapp/9wzdncrdfwbs

Regardless of region set when i'm clicking to "install" progress bar is blinking ones just for milliseconds and nothing happens , same was with debian, but i have installed debian after update, now i have the same problem with whatsapp.

How the hell people can fuc$@% up main tool for getting apps and push the update ? lol (I mean windows store) in nowadays "app stores are so freakingly important for dummy users (90% of sales target for OS) that it must work. Why OS X is so popular ? because it works, same with linux.

But I can say Windows looks nicer an even better when customized in dark themes., i need it because some automation systems need native windows, and there is no adobe cc for linux, and my MBP15 is a bit too big for handling when programming automation on-the-go , and there is no 12" that has LAN big USB and NFC and chipcard reader , or lcd with touch interface in Apple stables, so Dell must be in my bag, but day after day i see bugs. 20 yeas+ of using onlu *NIX and now i need windows for the first time (i'm 38) :D 

If i can help in other ways just post me.

**Comment by samirgunic** [comment]
Thank you for confirming!

So the WSL short link is not wrong _per se_, as it resolves properly. It's the back-end part of the Microsoft Store that's not working properly if you have the location set to anything other than United States. Not much we can do about that on the documentation side of WSL. This needs to be taken up in a Windows or Microsoft Store specific repo, which doesn't exist of course, with Windows being proprietary and all that. I will make sure to add it as feedback in the Feedback hub.

(As for the WhatsApp app, I was able to install it. Both with location set to Poland, Sweden and United States.)
