### ISSUE TITLE
Cannot upgrade to version 2 even when Virtual Machine Platform is enabled

### ISSUE THREAD

**Issue by iggyvolz** [MicrosoftDocs/WSL#404]
I have enabled the VirtualMachinePlatform as instructed, but I am still unable to upgrade my distribution to version 2:
```
PS C:\WINDOWS\system32&gt; Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform


Path          :
Online        : True
RestartNeeded : False



PS C:\WINDOWS\system32&gt; wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature.
PS C:\WINDOWS\system32&gt; wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by LaurentLienhard** [comment]
Reboot After enable-Windows feature ?

**Comment by janjiss** [comment]
I'm facing the same issue, even after reboot

**Comment by greywulf** [comment]
Same issue here. It could be that Virtual Machine Platform cannot be installed on Windows 10 Home Insider Preview, making this a Pro only feature. I hope that is not the case.

**Comment by matthieugauthier** [comment]
Same issue, "Virtual Machine Platform" is checked on Features Panel, but still print "Please enable the Virtual Machine Platform Windows feature." .

**Comment by wrvsrx** [comment]
Same issue, and I installed Windows 10 Pro Insider Preview.

**Comment by wrvsrx** [comment]
I solved it on my PC. 
Virtual Machine Platform needs "Virtualization"(or other similar options) option set to "Enabled" in UEFI. But if you open it with Powershell, system won't check if "Virtualization" option is set to enabled. 
So setting the option in UEFI may solve this problem(at least it works on my PC).

**Comment by iggyvolz** [comment]
Enabling virtualization appears to be working on my system; I can't believe I didn't think of doing that.  The error message and/or docs should be updated to reflect that you need virtualization on as well.

**Comment by benhillis** [comment]
Good suggestion, I will update the error message and documentation.

**Comment by dmserrano** [comment]
I am attempting to install WSL 2 on Parallels Desktop 14 Home Edition, but it seems the enabling virtualization feature (Parallels calls it Nested Virtualization) has been moved to the Pro edition only.

Is there another way to enable virtualization or am I out of luck while using Home Edition? I apologize if there is a simple fix for this, I am new to Windows.

**Comment by scyto** [comment]
I hit same issue, hadn't realized a BIOS upgrade had turned off VT - thanks.
@microsoft if the conversion command exits immediately it show an error message that VT is not enabled....

**Comment by scyto** [comment]
i mean it *should*  show an error

**Comment by rweaver6** [comment]
I had the same issue due to virtualization being disabled in BIOS. 

Before the fix, Bash shell command uname says it's running Linux 4.4. I guess that's what the MS system call emulator call itself.

In Powershell, the conversion command...

  wsl --set-version Ubuntu 2

...should print "Conversion complete."
It did take a few minutes.

PS C:\WINDOWS\system32> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         2

After the fix, the real Linux kernel is running in a VM, so the kernel's uname version is 4.19 :

bob@craterlake:~$ uname -a
Linux craterlake 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

(note: craterlake is just the name of my PC)

Apparently this kernel was compiled over lunch on May 20 :-)

**Comment by MdMaksudulHossain** [comment]
"Please enable the Virtual Machine Platform Windows feature." same problem for me too. Did anyone get any easy fix?

**Comment by matthieugauthier** [comment]
I fix it by launching both commands in an admin terminal. Use another session cause error message appear.

**Comment by albertowar** [comment]
Even with virtualization enabled in the BIOS and those two features enabled via Powershell, I still get this error:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370109
Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.
```

**Comment by winecos** [comment]
the same issue under Surface Book 2 .
i can't find the VT option and then to enable it  in UEFI panel of Surface Book 2 .
so , anybody else have solutions ? 
thx

**Comment by MdMaksudulHossain** [comment]
Hello all,
My laptop is Lenovo G40.
1. I had to change the windows version to 1903 (OSbuild 18917) to complete
the installation (can check your version by typing winver).
2. I had to go to the Windows Update Assistant for the version update and
changed the insider setting to "fast" to get the build upgrade the next
day. 3. After enabling virtual machine environment through PowerShell
(admin), it still showed "virtualization not enabled". For lenovo G40,
after shutdown, I used novo button to go to bios set up and enable intel
virtualization. (doesn't show the UEFI option through windows 10).
Then all the commands worked and it's showing wsl version 2.

One more question: when is the windows terminal going to be available? Can
I use that now? I am a beginner.

**Comment by tristanbarcelon** [comment]
Is WSL 2 available on the recently released Windows Server 18917 SAC (core edition) ISO? I've already enabled VirtualMachinePlatform feature and rebooted. Yet, wsl is not a valid command. I did install Microsoft-Windows-Subsystem-Linux but this appears to be v1.

**Comment by blkwtch** [comment]
Unable to execute WSL commands as the flags --set-version and --list --verbose are unknown
i tried to upgrade to WSL2 right after finishing the system upgrade to Version 10.0.18362 Build 18362

**Comment by tristanbarcelon** [comment]
18362 is still less than 18917 and wsl v2 requires 18917 or newer. In addition, documentation fails to mention that to get WSL, you also need to enable this feature: Microsoft-Windows-Subsystem-Linux in addition to VirtualMachinePlatform just for WSL to be a valid command.

**Comment by mscraigloewen** [comment]
@tristanbarcelon the [WSL 2 install docs](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) have been updated to include build number required and that you need WSL installed with a link of how to do so. 

This thread is for the specific issue of seeing the error 'Please enable the virtual machine platform' when it is already enabled, and we're working on resolving that error. If you have other questions, or issues, I'd ask that you please open a new issue so we can address them there. Thanks for your help!

**Comment by scyto** [comment]
@tristanbarcelon  
The here link has the content for that, though i agree having the command in the main install doc would make things easier @mscraigloewen.  I suspect @tristanbarcelon didn't read that / follow the here - maybe adding the command to the doc would make more sense than linking out.

`Please note that you'll need to be running Windows 10 build 18917 or higher to use WSL 2, and that you will need to have WSL already installed (you can find instructions to do so here).`

**Comment by tristanbarcelon** [comment]
@mscraigloewen , sorry didn't mean to cross post. I did follow WSL 2 install docs posted and nowhere does it state that WSL (v1) must already be installed. Once WSL v1 was installed, everything does work. If VirtualMachinePlatform is being enabled, is it checking to see whether virtualization features are enabled? In my situation, I installed Winows 10 18917 on a VM but I had forgotten to enable virtualization features before attempting to install WSL 1/2. It required me to delete, recreate the vm, run `Set-VMProcessor -VMName 'vmname' -ExposeVirtualizationExtensions $true -Force`, and re-install Windows 10 18917 or newer before re-attempting WSL 2 installation.

**Comment by mscraigloewen** [comment]
@scyto I've added the command to enable WSL to the troubleshooting section of the install page to make it clearer for users running into a similar issue. 

@tristanbarcelon no I don't believe DISM does check for that. 

I believe the sidebar conversation's are now resolved, so please for any further questions or comments that aren't related to the original issue I'd request that you open a new issue and we can continue the discussion there rather than cluttering notifications of users watching this specific issue.

**Comment by titaneric** [comment]
Left some tips for installing Windows in VM.

I installed Windows 10 in VMware Workstation, and the build version is 18922.
At the first time, I face the same issue. However, just like @wrvsrx said, I managed to turn on the virtualization on the CPU, so I used the following procedure performing on VMware Workstation:

1. Turn off the guest Windows.
2. Click on the upper tab and select the "VM" .
3. Click on the "Setting".
4. Stay in "Hardware" tab.
5. Click the "Processors" Device.
6. Check the "Virtualization Intel VT-x/EPT or AMD-V/RVI".
7. Boot the guest and upgrade the WSL again.

After that, I successfully upgrade my WSL to version 2. Thanks for all you comments.

**Comment by Radio-Broadcast** [comment]
I have checked that virtualization is enabled I'm still getting errors:
0xc03a001a - operation could not be completed due to a virtual disk system limitation. 
or
Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container. 

depending on how I try and get Ubuntu to update to wsl 2

**Comment by MdMaksudulHossain** [comment]
Hello all,

I upgraded to new windows 10 for using wsl2. I am now running into a lot of
troubles.

1. My microsoft store is no longer working. It says you are not connected
to the internet, although wifi is connected, I can browse, download
everything.

2. Now even better: my WSL, WSL2 stopped working altogether. If I run
bash.exe, it says "A device attached to the system is not functioning.".
Nothing is attached. What happened, no clue.

Does anyone have any suggestions for me? I feel like this is the dumbest
thing I have done ever.

Regards



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/26/19,
06:17:01 PM

**Comment by SteveALee** [comment]
As described in #436 I was getting 0x80370102 and as suggested by @mscraigloewen I enabled  virtualization in the horrid HP / AM BIOS.

But then ended up in a weird state where the store throught Ubuntu was installed and let me launch it but `wsl` said nothing was available. In case this was due to Ubuntu being installed as old WSL I uninstalled and re installed but install now fails with 0x80073D05

I tried re enabling the Platform and WSL but they were happy and said no reset needed.

So now I'm stuck :)

**Comment by SteveALee** [comment]
So I did another restart anyway and it did someththing. Now all errors have gone away. Lovely and fast now too :) 

And with the new terminal I feel like I've finally got a Bash environment I've been wanting since windows 3.1 :).

You might like to add 0x80370102 to the error already listed for BIOS needs installing.

**Comment by mscraigloewen** [comment]
@SteveALee added!

**Comment by rsrini7** [comment]
Windows Home 18922 Build. I am getting below error.
system32 $ wsl --set-version WLinux 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Unspecified error

**Comment by mscraigloewen** [comment]
There are a set of fixes coming out in the next Windows Insiders build that will address many of the issues in this thread. Once that is released please install the new build and try again!

**Comment by AliAskari** [comment]
I have followed on instructions in the document and followed the FAQ. I have Windows insider version 18932 and I am still facing this issue

```
0xc03a001a - operation could not be completed due to a virtual disk system limitation.
or
Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.
```

@mscraigloewen What is the insider build version that you expect would address these issues?

**Comment by taoyichen** [comment]
> I have followed on instructions in the document and followed the FAQ. I have Windows insider version 18932 and I am still facing this issue
> 
> ```
> 0xc03a001a - operation could not be completed due to a virtual disk system limitation.
> or
> Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.
> ```
> 
> @mscraigloewen What is the insider build version that you expect would address these issues?

Same issue, build 18932.1000 190628-1650

**Comment by taoyichen** [comment]
@AliAskari Got it working!. I remembered reading that WSL 2 requires hyper-v. So I enabled hyper-v and container. Reboot. And Things worked.

**Comment by mscraigloewen** [comment]
@AliAskari a new Insiders build will be released in the future that will address some of these installation issues. For your issue specifically I'd recommend double checking in your BIOS that virtualization is enabled, and that your Virtual Machine Platform component is enabled.

**Comment by rsrini7** [comment]
Windows Insider build : 18932

WLinux migrated to wsl2. Post migration dockerd not starting.

time="2019-07-06T12:35:24.385197200+05:30" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.43-microsoft-standard/modules.dep.bin'\nmodprobe: WARNING: Module bridge not found in directory /lib/modules/4.19.43-microsoft-standard\nmodprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.43-microsoft-standard/modules.dep.bin'\nmodprobe: WARNING: Module br_netfilter not found in directory /lib/modules/4.19.43-microsoft-standard\n, error: exit status 1"
time="2019-07-06T12:35:24.386495900+05:30" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.43-microsoft-standard/modules.dep.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.19.43-microsoft-standard`, error: exit status 1"
time="2019-07-06T12:35:24.387748100+05:30" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.43-microsoft-standard/modules.dep.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.19.43-microsoft-standard`, error: exit status 1"
time="2019-07-06T12:35:24.410128900+05:30" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
time="2019-07-06T12:35:24.410615600+05:30" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
time="2019-07-06T12:35:24.410643100+05:30" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
time="2019-07-06T12:35:24.411191200+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420644480, TRANSIENT_FAILURE" module=grpc
time="2019-07-06T12:35:24.411214100+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420644480, CONNECTING" module=grpc
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables --wait -t nat -N DOCKER: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING

**Comment by mscraigloewen** [comment]
@rsrini7 please open a new issue inside of the [WSL Github repo](https://github.com/microsoft/wsl/issues) for that issue. This thread is for installation problems related to the Virtual Machine platform component.

**Comment by rsrini7** [comment]
Thanks @mscraigloewen 
But Same issue found : #4165

**Comment by naymore** [comment]
Same issue.
Virtualization is enabled in this BIOS.

I also had trouble setting up docker for windows in a Hyper-V VM (nested virtualization).
Maybe this is related?

Win 10 (1903) host running a Win 10 (insider fast ring) VM attempting to run WSL 2

**Comment by eshernan** [comment]
>  wsl --set-version (no valid command). 
I'm part of Windows Inside Program with "Release Preview" active, but in my Windows Update don´t appear the Build  18917. How I can fix this problem to install  WSL 2 ?

**Comment by titaneric** [comment]
@eshernan, you may choose the "fast preview" in order to get the latest update.
My host computer get at least Build 18936 version whilst turning on the fast ring.

**Comment by MichaelE919** [comment]
This is still happening for me. I've check BIOS to ensure that virtualization is enabled. I've also disabled Virtual Machine Platform and Windows Subsystem for Linux and re-enabled them. When I first tried this a few weeks ago it worked for me and I used WSL 2 for a while. I had to install VirtualBox for something and it didn't work initially. I converted back to WSL 1 I remember having to change a setting or two but I can remember what I did. I have since uninstalled VirtualBox and followed the WSL 2 steps. No luck.

**Comment by lgosselin** [comment]
I'm also experiencing difficulties to enable WSL2 at all given the instructions in the documentation. 
I have the exact same output as the OP: Virtual Machine Platform Windows feature is enabled, the conversion starts then finally ask to enable Virtual Machine Platform Windows.

Has anyone tried to make it work in virtualization case with a KVM hypervisor? 

I clearly don't expect to find the documentation on how to proceed on Microsoft docs site but I'd be delighted to have a set of prerequisites for WSL2 activation (as well as more fine grained error message when it cannot be enabled)

Additional info: 

* I'm running a guest Win10Pro insider 18941 (fast ring) under KVM on a Linux host. Host is setup to allow nested virtualization (`nested=Y` for `kvm_intel` module) in case it would be needed (and given the comments here I guess it is). The guest CPU has `vmx` feature enabled (to support virtualization) and, if it makes any difference, it has its own SATA controller + dedicated disk and graphical adapter. 

* Task manager, tab Performance does not display `Virtualization: Enabled` (and I guess it should to have WSL2 working?)

I suppose my failure to activate WSL2 is linked to this particular setup. Can anyone advise?

**Comment by ciarancourtney** [comment]
> I'm also experiencing difficulties to enable WSL2 at all given the instructions in the documentation.
> I have the exact same output as the OP: Virtual Machine Platform Windows feature is enabled, the conversion starts then finally ask to enable Virtual Machine Platform Windows.
> 
> Has anyone tried to make it work in virtualization case with a KVM hypervisor?
> 
> I clearly don't expect to find the documentation on how to proceed on Microsoft docs site but I'd be delighted to have a set of prerequisites for WSL2 activation (as well as more fine grained error message when it cannot be enabled)
> 
> Additional info:
> 
> * I'm running a guest Win10Pro insider 18941 (fast ring) under KVM on a Linux host. Host is setup to allow nested virtualization (`nested=Y` for `kvm_intel` module) in case it would be needed (and given the comments here I guess it is). The guest CPU has `vmx` feature enabled (to support virtualization) and, if it makes any difference, it has its own SATA controller + dedicated disk and graphical adapter.
> * Task manager, tab Performance does not display `Virtualization: Enabled` (and I guess it should to have WSL2 working?)
> 
> I suppose my failure to activate WSL2 is linked to this particular setup. Can anyone advise?

I'm in the same boat, only my VM is on vmware ESX 5. I enabled nested virtualization for Android Studio emulator support months ago, a recent update removed the `Virtualization: Enabled` from Task Manager, likely inaccurate.

**Comment by mscraigloewen** [comment]
For everyone experiencing install related issues please update to the latest Windows Insider Build: 18945, we've added in fixes to the install process. 

You can read more about the overall changes in this build [here](https://blogs.windows.com/windowsexperience/2019/07/26/announcing-windows-10-insider-preview-build-18945/) and the WSL specific ones [here](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-insiders-preview-build-18945/). Thanks!

**Comment by rsrini7** [comment]
Thanks. Once updated my windows its rollback to 18932. 
Tried multiple times but all failed.

**Comment by mhcassiem** [comment]
> I have checked that virtualization is enabled I'm still getting errors:
> 0xc03a001a - operation could not be completed due to a virtual disk system limitation.
> or
> Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.
> 
> depending on how I try and get Ubuntu to update to wsl 2
> 
> Edit: I got it working:
> I manually changed the folder properties of the directory where Ubuntu is installed and disabled encryption and compression in the advanced settings tab of the folder attributes.

I can confirm that this worked for me. Thank you

**Comment by MdMaksudulHossain** [comment]
Whenever I try to type bash in cmd or wsl in Powershell it says: "A device
connected to the system is not functioning" after I activate the windows
subsystem in Linux. Nothing is connected to the laptop.

Can anyone help me?

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/27/19,
09:07:06 PM

**Comment by mscraigloewen** [comment]
@MdMaksudulHossain please check out [this](https://github.com/microsoft/WSL/issues/4155) issue on our WSL repo page, it might help you out.

**Comment by MaximoTrinidad** [comment]
Well, in my case, two to three insider versions ago, I was happy to see WSL-2 working on my VM in VMWare Workstation Pro and with Docker client loaded in WSL-2.  

Now, I change my environment to use Hyper-V in my Windows 10 production client machine, then installed Window 10 Insider to Build 18950... and, I can't even install WSL-1.  

Getting the error message: (Ubuntu 18.04)
```
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
```

No matter what I do.  I remove all components and reinstalled them back.  I'm on a dead end!

I'm upgrading now to Windows 10 Insider Build 18956 and pray to see if something will work.

![WSLerr_01_2019-08-07_16-25-45](https://user-images.githubusercontent.com/19892435/62656415-21517280-b932-11e9-8256-90430d966429.png)

![WSLerr_02_2019-08-07_16-25-45](https://user-images.githubusercontent.com/19892435/62656546-670e3b00-b932-11e9-8f6f-7b4097d1f29c.png)

**Comment by beardedeagle** [comment]
I have all VT settings enable except for trusted installer in bios, hyper-v, wsl and windows virtual machine platform installed. It simply doesn't recognize the command as valid to update Ubuntu to version 2. I've tried uninstalling and rebooting, then installing one at a time with a reboot in between. No go. I'm on version 1903.

```
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux         

Path          : 
Online        : True
RestartNeeded : False

PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform                    

Path          :
Online        : True
RestartNeeded : False

PS C:\WINDOWS\system32> wsl --list --all
Windows Subsystem for Linux Distributions:
Ubuntu (Default)

PS C:\WINDOWS\system32> wsl --set-default-version 2
Invalid command line option: --set-default-version
```

**Comment by abner-w** [comment]
Hi, everyone. if you make sure the "Virtual Machine Platform", "Hyper-V", "Windows Subsystem for Linux" is checked on your Windows Features.  and trun on the "CPU Virtualization" on your BIOS.
when you run the upgrade cmd "wsl --set-version <Ubuntu/xxxx> 2", and still receive "Please enable the Virtual Machine Platform Windows feature."
you can check the "Hyper-V vmcompute services"(spelled correctly? my win10 is Chinese language.) is running?
i try to start the service , and got some error like "cat't start the Hyper-V ...., error code 1503?". 
and, i follow this guide to fix this problem. (https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt&prof=required)
finally, i try to run "wsl --set-version <Ubuntu/xxxx> 2", and it's worked !
hope can help someone?

**Comment by Polda18** [comment]
I cannot upgrade to WSL 2, because this is when I try to use `wsl --set-version Ubuntu 2`:
```
Invalid command line option: --set-version
```

I can't seem to be able to do anything about it.

**Comment by Polda18** [comment]
Just to clarify, I installed WSL 1 first, then enabled Virtual Machine feature. Both followed by machine reboot.

And yet this is what it shows to me:
https://ctrlv.cz/FcrS

**Comment by mxtrinidad** [comment]
**My Issue was resolved!!**
If running Windows 10 Insider as a guest Hyper-V, then the solution provider by @naymore solved my  issue.

Executing in PowerShell the command in the Hyper-V host machine: (VM need to be stopped)
```
## - To be executed on the Hyper-V host machine:
Set-VMProcessor -VMName [GuestVMName] -ExposeVirtualizationExtensions $true
```

This resolved my issue "error: 0x80370102 the virtual machine could not be started because a required feature is not installed." 

The error message is misleading as the features were already installed.  

![Error_fix_01_2019-09-09_12-46-44](https://user-images.githubusercontent.com/54905444/64550163-44d85600-d300-11e9-8f5c-fc9050f04787.png)

![Error_fix_02_2019-09-09_12-46-44](https://user-images.githubusercontent.com/54905444/64550784-a8af4e80-d301-11e9-88ce-d060508e389e.png)

**Comment by craigloewen-msft** [comment]
@Polda18 please check your Windows version and makes sure you're using build 18917 or higher. 

I'm closing this issue out since we have made many fixes to the install process, if you have more issues please open them on the WSL repo: https://github.com/microsoft/wsl

**Comment by earonesty** [comment]
Also, note: upgrading to WSL2 this way will break VirtualBox and probably other virtualization engines.   WSL2 is no longer a lightweight compatibility system... instead it's a full VM, with all the mount issues, etc of VM's.

**Comment by danielsballes** [comment]
I have virtualization enabled in Bios and still getting this error, what is happening?

**Comment by craigloewen-msft** [comment]
Hi @danielsballes you can double check if virtualization is enabled by going to Task Manager->Performance and looking at the CPU tab.
![image](https://user-images.githubusercontent.com/42221804/69985003-41173280-14ef-11ea-936b-8d0172360ad5.png)

Then please make sure the 'Virtual Machine Platform' optional component is enabled.
![image](https://user-images.githubusercontent.com/42221804/69985079-6efc7700-14ef-11ea-803c-52f453cb3c1a.png)

If you're still receiving errors after that please open an issue on the [WSL Github repo](https://github.com/microsoft/wsl)
 (This one is for the documentation only). Thanks!

**Comment by hrai** [comment]
I had to run this command in powershell then restart the computer.

`bcdedit /set hypervisorlaunchtype auto start`

**Comment by kunzig940** [comment]
After running `bcdedit /set hypervisorlaunchtype auto start` as described above my windows fails to boot. If anyone knows how to undo I'd appreciate it.

**Comment by freegnu** [comment]
Uninstalling Windows Subsystem for Linux Update and then reinstalling it fixed the problem without requiring a reboot. I verified that WSL 1 was working by installing a second WSL Linux Ubuntu 18.04 from the MS Store that worked fine while the WSL 2 upgraded Linux for Ubuntu from the MS Store complained about upgrading the kernel. I tied all the other stuff but WSL 2 was previously working fine. Also these 2 commands are a lifesaver and fix the MS Store not working and other weird broken Windows stuff.
    sfc /scannow
    dism /online /cleanup-image /restorehealth

**Comment by luminiscence** [comment]
I've turned on slow ring of Insider Preview program,
![image](https://user-images.githubusercontent.com/15375180/80788559-a2812180-8bb3-11ea-9bfd-459ccb842744.png)
Checked that virtualization is enabled
![image](https://user-images.githubusercontent.com/15375180/80788465-65b52a80-8bb3-11ea-9961-3d2e1687f1b5.png)
Windows subsystem for Linux and Virtual Machine Platform components are also installed
![image](https://user-images.githubusercontent.com/15375180/80788634-e1af7280-8bb3-11ea-9ff7-1466dc38f95b.png)
And even more, yesterday I played with vagrant with VirtualBox virtual machine and all went fine. WSL1 also worked for me, but with WSL2 I have this
![image](https://user-images.githubusercontent.com/15375180/80788744-26d3a480-8bb4-11ea-8633-9928978ec812.png)
and have no idea what I can do to fix it. WSL1, as mentioned before, is also broken, so instead of having new feature I've lost existing. Can you help me?

**Comment by MdMaksudulHossain** [comment]
Hi all,
Whenever I try to use  sudo apt-get update && sudo apt-get upgrade
it shows the following error:
 Temporary failure resolving 'archive.ubuntu.com'

Can anyone please share some thoughts?

Md Maksudul Hossain

Graduate Research Assistant

**Comment by freegnu** [comment]
> I've turned on slow ring of Insider Preview program,
> ![image](https://user-images.githubusercontent.com/15375180/80788559-a2812180-8bb3-11ea-9bfd-459ccb842744.png)
> 
> checked that virtualization is enabled
> ![image](https://user-images.githubusercontent.com/15375180/80788944-c85af600-8bb4-11ea-9955-dd0532d19c90.png)
> 
> Windows subsystem for Linux and Virtual Machine Platform components are also installed
> ![image](https://user-images.githubusercontent.com/15375180/80788857-7d40e300-8bb4-11ea-9b25-c31bcc047a90.png)
> 
> And even more, yesterday I played in vagrant with VirtualBox virtual machine and all went fine. WSL1 also worked for me, but with WSL2 I have this
> ![image](https://user-images.githubusercontent.com/15375180/80788744-26d3a480-8bb4-11ea-8633-9928978ec812.png)
> 
> WSL1, as mentioned before, is also broken, so instead of having new feature I've lost existing. Can you help me?
> 
> P.S. Info from CPU-Z
> ![image](https://user-images.githubusercontent.com/15375180/80790475-2558ab00-8bb9-11ea-8a41-87aeedcc01a2.png)

WSL 2 isn't available in non-Preview until update 2004.

**Comment by beaverlyhillsstudios** [comment]
> I have checked that virtualization is enabled I'm still getting errors:
> 0xc03a001a - operation could not be completed due to a virtual disk system limitation.
> or
> Error: 0x80370109 The operation timed out because a response was not received from the virtual machine or container.
> 
> depending on how I try and get Ubuntu to update to wsl 2
> 
> Edit: I got it working:
> I manually changed the folder properties of the directory where Ubuntu is installed and disabled encryption and compression in the advanced settings tab of the folder attributes.

worked for me, uncompressed AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows...

**Comment by birdmanmandbir** [comment]
@freegnu same problem on 2004..

**Comment by flaprano** [comment]
> @freegnu same problem on 2004..

The same happening here.
Almost giving up on use WSL. The support seems pretty bad.

**Comment by birdmanmandbir** [comment]
@flaprano You can try solutions in this issue: [wsl-#5328](https://github.com/microsoft/WSL/issues/5328)

**Comment by MaximoTrinidad** [comment]
Guys!!

There's a WSL update patch (wsl_update_x64.msi) that needs to be installed before you convert the WSL1 to 2.

I had the situation that I had to run it twice before it started working.
:)

**Comment by NicTanghe** [comment]
hello so wsl 1 doesn`t even work.
im also on windows 2004

**Comment by MaximoTrinidad** [comment]
Yes! There was a link to update the WSL 2 Kernel:
https://aka.ms/wsl2kernel

In my case, I had to run it twice, and everything is working.

![WSL2-Update_2020-05-28_9-08-10](https://user-images.githubusercontent.com/19892435/83912283-97358e80-a73b-11ea-9d98-548a82ce27f5.jpg)

**Comment by Vishnu05** [comment]
> I am attempting to install WSL 2 on Parallels Desktop 14 Home Edition, but it seems the enabling virtualization feature (Parallels calls it Nested Virtualization) has been moved to the Pro edition only.
> 
> Is there another way to enable virtualization or am I out of luck while using Home Edition? I apologize if there is a simple fix for this, I am new to Windows.

Yeah, same here, needed some help to resolve this

**Comment by Robinzon100** [comment]
the version 2 upgrade worked after I enabled intel virtualization technology in **BIOS>advance**, 
if you can't find what I'm talking about or where's the option ill be glad to take pictures of the bios 

good luck everybody and have a beautiful day

**Comment by freegnu** [comment]
I find the final solution when nothing else gets Windows 10 to behave as it
should. Run the upgrade after downloading the Windows 10 installer/upgrader
from Microsoft. Make sure the installer is for the same version of Windows
10 as you have installed AKA 2004 at this point in time. Fixes all major
problems immediately without having to reinstall or recreate your account,
settings, and apps but doesn't prevent the bit rot from settling in again
over time.

**Comment by MdMaksudulHossain** [comment]
Hello,

When I try to sudo apt-get update or upgrade, it shows the follows error:
Temporary failure resolving 'archive.ubuntu.com'
Mine is wsl2 and I am using Ubuntu 20.04.1 LTS. ping is not working either.
It says "ping: google.com: Temporary failure in name resolution"
It was working fine before. I have tried a few solutions e.g. changing
nameserver in /etc/resolv.conf, removing this file. Can anyone help me,
please?

**Comment by scyto** [comment]
@MdMaksudulHossain  assuming you don't have fundamental connectivity issue try this https://github.com/microsoft/WSL/issues/5256#issuecomment-667751572

**Comment by MdMaksudulHossain** [comment]
Dear altruists,
I installed chocolatey, fluent terminal, zsh, Oh My ZSH yesterday to get
some new experience. It was all going well. I could run both windows
terminal and fluent terminal. Today WSL is no longer launching. I have
tried wsl, bash, windows terminal, ubuntu terminal everything. All of them
just show a cursor on a blank screen, nothing really starts. What could
possibly go wrong?

Best regards,
Maksud

**Comment by freegnu** [comment]
I had this happen on Windows Terminal. I had upgraded my bios and the CPU
virtualization was off by default in the bios.

**Comment by RenanZX** [comment]
I have AMD processor, same problem

**Comment by shmuli9** [comment]
> Yes! There was a link to update the WSL 2 Kernel:
> https://aka.ms/wsl2kernel
> 
> In my case, I had to run it twice, and everything is working.
> 
> ![WSL2-Update_2020-05-28_9-08-10](https://user-images.githubusercontent.com/19892435/83912283-97358e80-a73b-11ea-9d98-548a82ce27f5.jpg)

Reinstalling the WSL2 kernel fixed the issue for me

Thanks

**Comment by codepolariz** [comment]
> I have enabled the VirtualMachinePlatform as instructed, but I am still unable to upgrade my distribution to version 2:
> 
> ```
> PS C:\WINDOWS\system32&gt; Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
> 
> 
> Path          :
> Online        : True
> RestartNeeded : False
> 
> 
> 
> PS C:\WINDOWS\system32&gt; wsl --set-version Ubuntu 2
> Conversion in progress, this may take a few minutes...
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> Please enable the Virtual Machine Platform Windows feature.
> PS C:\WINDOWS\system32&gt; wsl --list --verbose
>   NAME      STATE           VERSION
> * Ubuntu    Stopped         1
> ```
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: b19a43be-b16a-d903-b69d-75dffce6c329
> * Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
> * Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)
> * Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
> * Product: **windows-subsystem-for-linux**
> * GitHub Login: @mscraigloewen
> * Microsoft Alias: **mscraigloewen**


> > I've turned on slow ring of Insider Preview program,
> > ![image](https://user-images.githubusercontent.com/15375180/80788559-a2812180-8bb3-11ea-9bfd-459ccb842744.png)
> > checked that virtualization is enabled
> > ![image](https://user-images.githubusercontent.com/15375180/80788944-c85af600-8bb4-11ea-9955-dd0532d19c90.png)
> > Windows subsystem for Linux and Virtual Machine Platform components are also installed
> > ![image](https://user-images.githubusercontent.com/15375180/80788857-7d40e300-8bb4-11ea-9b25-c31bcc047a90.png)
> > And even more, yesterday I played in vagrant with VirtualBox virtual machine and all went fine. WSL1 also worked for me, but with WSL2 I have this
> > ![image](https://user-images.githubusercontent.com/15375180/80788744-26d3a480-8bb4-11ea-8633-9928978ec812.png)
> > WSL1, as mentioned before, is also broken, so instead of having new feature I've lost existing. Can you help me?
> > P.S. Info from CPU-Z
> > ![image](https://user-images.githubusercontent.com/15375180/80790475-2558ab00-8bb9-11ea-8a41-87aeedcc01a2.png)
> 
> WSL 2 isn't available in non-Preview until update 2004.

Are you using a virtual machine? if yes you need to enable nested virtualization. In my case, i am using parallel and i faced the same issue. After enabling nested virtualization, WSL2 WORKED. 
Follow the steps on this link or if you are using VMware or Virtualbox nested virtualization is bundled with the VM by default
https://patrickwu.space/2020/02/14/wsl-on-mac/

**Comment by f3ndot** [comment]
> After running `bcdedit /set hypervisorlaunchtype auto start` as described above my windows fails to boot. Had to run `bcdedit /set hypervisorlaunchtype off` to undo.

This also caused my machine not to boot. Trying to undo by running the other command didn't work in safe mode's command prompt. I'm stuck in a failed Win10 boot loop :(

Buyer beware

**Comment by freegnu** [comment]
Try running  Dism.exe /online /Cleanup-Image /StartComponentCleanup & dism
/online /cleanup-image /restorehealth & sfc /scannow

**Comment by danieldejesus8745** [comment]
I managed to update to wsl2 like this:

1. I ran the command "wsl" in the power shell adm

2. I opened another instance of the power shell and ran the command "wsl.exe --set-default-version Ubuntu 20.04 2"

**Comment by yiqiangjizhang** [comment]
I have the same issue, read all the Issueas above but none of them are working for me!
Here is what I get:
![image](https://user-images.githubusercontent.com/68460056/109623819-d31c4980-7b3d-11eb-8c46-d456a1761d98.png)

**Comment by o-mono** [comment]
try this:
`bcdedit /set hypervisorlaunchtype auto start` then `shutdown /r` in powershell as administrator

**Comment by freegnu** [comment]
wsl --set-version Ubuntu 2

**Comment by ReinWD** [comment]
> Try running Dism.exe /online /Cleanup-Image /StartComponentCleanup & dism /online /cleanup-image /restorehealth & sfc /scannow



> try this:
> `bcdedit /set hypervisorlaunchtype auto start` then `shutdown /r` in powershell as administrator

combination of these commands helped.
Just upgraded to WSL2.

**Comment by mlclmtan** [comment]
For those who have WSL1 installed, make sure to run `wsl --set-default-version 2` in powershell and `Windows subsystem for Linux and Virtual Machine Platform` components are also installed, then ready to upgrade to WSL2.
Simply **install any other version from store**, and open your original Ubuntu, remove the newly installed version, viola `wsl -l -v` it shows version 2!
