### ISSUE TITLE
Error 0x80370102 The Virtual machine could not be started because a required feature is not installed  ....

### ISSUE THREAD

**Issue by SteveALee** [MicrosoftDocs/WSL#436]
Following instructions on https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback with a fairly clean install of Build 18922

* enabled The VMPlatform, reboot
* enabled wsl, reboot
* `wsl set-default-verion 2`
* Install Ubuntu from store - https://aka.ms/wslstore as directed by `wsl -l -v`
* Launch Ubuntu

Get the above error.

**Comment by mscraigloewen** [comment]
Is virtualization enabled in your BIOS? That could be a quick fix.

We're tracking this issue over in #404 and we can help you troubleshoot there!

**Comment by SteveALee** [comment]
Ah, yes. I didn;t check as 0x80370102 is different error number to that listed for that issue. I forgot to enable it as Insiders Machine was not a dev PC. Still getting the error though. Will head over to #404 (a very suitable number) :D

**Comment by blackmasks** [comment]
I had a similar problem on when installing on my new system. I checked my BIOS @craigloewen-msft as mentioned. The first time I didn't find anything but after doing a bit more research I tried turning on SVM in the BIOS and it worked. (I also turned on the Windows Hypervisor setting in Windows Features)

(Advanced → CPU Configuration → SVM → Enable)

This is the case for AMD systems. Apparently it is different for Intel based systems.

**Comment by helloiamyeet** [comment]
Hi i am have i BIG issue with getting Kali Linux installed on my Windows 10 PC. i was having a problem with Kali it said that there were unmet dependencies. try 'apt --fix-broken install' with no packages (or specify a solution). and i looked it up and i just could not find anything to fix it so i was like "ok i will just uninstall and try a again later". but when i installed it again it will not even work like at ALL!! 
and this is the error (╯°□°）╯︵ ┻━┻

Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

but i have all the right "dependencies" #i say with sarcasm, pls pls pls help MeEeeE

**Comment by ManoloMoraes** [comment]
> Is virtualization enabled in your BIOS? That could be a quick fix.
> 
> We're tracking this issue over in #404 and we can help you troubleshoot there!

Thank you, i enable and work.

**Comment by itiscode** [comment]
> > Is virtualization enabled in your BIOS? That could be a quick fix.
> > We're tracking this issue over in #404 and we can help you troubleshoot there!
> 
> Thank you, i enable and work.

how did u do it

**Comment by ktmn** [comment]
"The Virtual machine could not be started because a required feature is not installed" 

How about make the message say *which* feature is not installed.

I got Virtualization enabled in BIOS, `Windows Subsystems for Linux` and `Virtual Machine Platform` enabled in Windows features, still get the message.
Do I need `Hyper-V` enabled? Do I need `Windows Hypervisor Platform`?

**Comment by kscott5** [comment]
Hi @ktmn ,

Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after
Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.

"#0x80370102 the #virtual #machine could not be started because a required feature is not installed."

C:\>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop. 

The above resolves the error and got me further. Now...

C:\>ubunutu.exe
Prompts with new username and password.

![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)

**Comment by helloiamyeet** [comment]
Yes I fix it thank you very much

**Comment by thomas-griffiths** [comment]
> "The Virtual machine could not be started because a required feature is not installed"
> 
> How about make the message say _which_ feature is not installed.
> 
> I got Virtualization enabled in BIOS, `Windows Subsystems for Linux` and `Virtual Machine Platform` enabled in Windows features, still get the message.
> Do I need `Hyper-V` enabled? Do I need `Windows Hypervisor Platform`?
> 
> Edit: no, enabling these 2 didn't solve it either.
> 
> Edit 2: running `bcdedit /set hypervisorlaunchtype auto start` and reboot seems to have worked for me. So maybe I _did_ need Hyper-V and/or Hypervisor Platform enabled, but it doesn't tell you anything useful.

This worked for me too.  Thank you.

**Comment by 12729582** [comment]
> ubunutu.exe

thank you thank you

**Comment by 12729582** [comment]
> Hi @ktmn ,
> 
> Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after
> Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> 
> "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> 
> C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> 
> The above resolves the error and got me further. Now...
> 
> C:>ubunutu.exe
> Prompts with new username and password.
> 
> ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)

thank you thank you

**Comment by dev-mtshikomba** [comment]
`$wsl --set-default-version 1`

This one solved it for me.

> Hi @ktmn ,
> 
> Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after
> Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> 
> "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> 
> C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> 
> The above resolves the error and got me further. Now...
> 
> C:>ubunutu.exe
> Prompts with new username and password.
> 
> ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)

This one solved it for me.

**Comment by pluc** [comment]
How about you come up with specific, non-stupid error messages so people don't have to go through this thread to identify what was the error?

**Comment by WhiteZorin** [comment]
@ktmn - THANK YOU! the below has solved the issue after days of trying random solutions from google/blogs/ms threads...

> Edit 2: running `bcdedit /set hypervisorlaunchtype auto start` and reboot seems to have worked for me. So maybe I _did_ need Hyper-V and/or Hypervisor Platform enabled, but it doesn't tell you anything useful.

Although it doesn't show any Hyper-V or Hypervisor platform to be turned on in "Turn windows features on". And in services.msc the only one working currently is: Hyper-V host compute service...

**Comment by gabrielkemec** [comment]
I had the same problem and changing the setting in my bios to enable VM fixed this issue, so try that too in case none of the commands above fixed it for you

**Comment by DarkChocolate** [comment]
> "The Virtual machine could not be started because a required feature is not installed"
> 
> How about make the message say _which_ feature is not installed.
> 
> I got Virtualization enabled in BIOS, `Windows Subsystems for Linux` and `Virtual Machine Platform` enabled in Windows features, still get the message.
> Do I need `Hyper-V` enabled? Do I need `Windows Hypervisor Platform`?
> 
> Edit: no, enabling these 2 didn't solve it either.
> 
> Edit 2: running `bcdedit /set hypervisorlaunchtype auto start` and reboot seems to have worked for me. So maybe I _did_ need Hyper-V and/or Hypervisor Platform enabled, but it doesn't tell you anything useful.

This worked for me as well, thank you!

**Comment by imperialguy** [comment]
> 
> 
> > "The Virtual machine could not be started because a required feature is not installed"
> > How about make the message say _which_ feature is not installed.
> > I got Virtualization enabled in BIOS, `Windows Subsystems for Linux` and `Virtual Machine Platform` enabled in Windows features, still get the message.
> > Do I need `Hyper-V` enabled? Do I need `Windows Hypervisor Platform`?
> > Edit: no, enabling these 2 didn't solve it either.
> > Edit 2: running `bcdedit /set hypervisorlaunchtype auto start` and reboot seems to have worked for me. So maybe I _did_ need Hyper-V and/or Hypervisor Platform enabled, but it doesn't tell you anything useful.
> 
> This worked for me as well, thank you!

None of them worked for me. I am running WSL2 on Windows 10 VM on proxmox with nested virtualization enabled. Task Manager on Windwows does show Virtualization: Enabled. All the program features are enabled as well. And I did all the steps mentioned above. Still doesn't work. Any ideas?

**Comment by NvkAnirudh** [comment]
> `$ wsl --set-default-version 1`
> 
> This one solved it for me.
> 
> > Hi @ktmn ,
> > Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after
> > Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> > "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> > C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> > The above resolves the error and got me further. Now...
> > C:>ubunutu.exe
> > Prompts with new username and password.
> > ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)
> 
> This one solved it for me.

This solved my issue too, thanks

**Comment by keeganparr** [comment]
I had to enable the "Virtualize Intel VT-x/EPT or AMD-V/RVI" setting in VMware Workstation under Hardware-->Processors.

**Comment by Chlerry** [comment]
> running `bcdedit /set hypervisorlaunchtype auto start` and reboot

This works for me as well.

**Comment by boobytrap** [comment]
Worked for me as well - Thank you.
In my HP laptop, the BIOS option I enabled is called "Virtualization Technology"

**Comment by FuzzieKiwi** [comment]
> Hi @ktmn ,
> 
> Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after
> Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> 
> "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> 
> C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> 
> The above resolves the error and got me further. Now...
> 
> C:>ubunutu.exe
> Prompts with new username and password.
> 
> ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)

Didn't realize my new mobo had virtualization disabled by default.

**Comment by talesmgodois** [comment]
dumb question, in my case, this is happening inside a vm... Can this work?

My scenario: I have a manjaro machine, which uses virtualbox to run a windows machine. I am trying to install a linux subsystem in this vm, should this work? I know that It might be too nestled

**Comment by nameldk** [comment]
> Edit 2: running `bcdedit /set hypervisorlaunchtype auto start` and reboot seems to have worked for me. So maybe I _did_ need Hyper-V and/or Hypervisor Platform enabled, but it doesn't tell you anything useful.

Thanks a lot. It's worked for me.

**Comment by Varrions** [comment]
> "The Virtual machine could not be started because a required feature is not installed"
> 
> How about make the message say _which_ feature is not installed.
> 
> I got Virtualization enabled in BIOS, `Windows Subsystems for Linux` and `Virtual Machine Platform` enabled in Windows features, still get the message.
> Do I need `Hyper-V` enabled? Do I need `Windows Hypervisor Platform`?
> 
> Edit: no, enabling these 2 didn't solve it either.
> 
> Edit 2: running `bcdedit /set hypervisorlaunchtype auto start` and reboot seems to have worked for me. So maybe I _did_ need Hyper-V and/or Hypervisor Platform enabled, but it doesn't tell you anything useful.

Thank you so much, it worked.

**Comment by kelli217** [comment]
I am also having this nonspecific error when I try to get WSL working. I've tried several different distros, turned on all the parts of various virtualization features and virtual machines, and it still gives me this problem. I think my computer is just too limited.

**Processor	Intel(R) Celeron(R) CPU  N2930  @ 1.83GHz, 1827 Mhz, 4 Core(s), 4 Logical Processor(s)**

I think this processor just doesn't support Hyper-V. The BIOS settings have virtualization turned on, verified _repeatedly,_ and still I get:

**Hyper-V - Virtualization Enabled in Firmware	No**

So at this point, I think it's just because my computer is a low-end machine aimed at the education market and just doesn't have the capability to do this. I guess I'll just stick to switch-booting.

**Comment by omidkrad** [comment]
### Docker+WSL2 in a VM

I was trying to run Docker+WSL2 inside a Hyper-V Virtual Machine, and after trying hundreds of things this is the solution that worked for me:

- In the VM, make sure you have "Virtual Machine Platform" and "Windows Subsystem For Linux" features enabled.
```powershell
Enable-WindowsOptionalFeature -Online -FeatureName $("VirtualMachinePlatform", "Microsoft-Windows-Subsystem-Linux")
```
- Shut down the VM.
- On the host, run the following command to enable Virtualization on your VM. This is equivalent to going in the BIOS and enabling Virtualization.
```powershell
Set-VMProcessor <VMName> -ExposeVirtualizationExtensions $true
```
or alternatively, you can run this to enable Virtualization on all the VMs that are turned off.
```powershell
Get-VM | ? State -eq 'Off' | Set-VMProcessor -ExposeVirtualizationExtensions $true
```
- Turn the VM back on.
- Now in Task Manager, under Performance tab, you should see that Virtualization is enabled.
- Before installing the [Linux distro](https://aka.ms/wslstore) make sure your default WSL version is 2:
```
wsl --set-default-version 2
```
or if the distro is already installed, check its WSL version:
```
wsl --list --all --verbose
```
and if it is 1, change it to 2:
```
wsl --set-version Ubuntu 2
```

Now you should be able to run Docker on WSL2 inside the VM.

These are the related error messages I put here to be searchable:

Error when launching Ubuntu for the first time:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
```

Error when running `wsl --set-version Ubuntu 2`:
```
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
```

Error when launching Docker Desktop:
```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\username\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install
```

**Comment by omidkrad** [comment]
### Docker+WSL2 in a VM

I was trying to run Docker+WSL2 inside a Hyper-V Virtual Machine, and after trying hundreds of things this is the solution that worked for me:

- In the VM, make sure you have "Virtual Machine Platform" and "Windows Subsystem For Linux" features enabled.
```powershell
Enable-WindowsOptionalFeature -Online -FeatureName $("VirtualMachinePlatform", "Microsoft-Windows-Subsystem-Linux")
```
- Shut down the VM.
- On the host, run the following command to enable Virtualization on your VM. This is equivalent to going in the BIOS of the VM and enabling Virtualization.
```powershell
Set-VMProcessor <VMName> -ExposeVirtualizationExtensions $true
```
or alternatively, you can run this to enable Virtualization on all the VMs that are turned off.
```powershell
Get-VM | ? State -eq 'Off' | Set-VMProcessor -ExposeVirtualizationExtensions $true
```
- Turn the VM back on.
- Now in Task Manager, under Performance tab, you should see that Virtualization is enabled.
- Before installing the [Linux distro](https://aka.ms/wslstore) make sure your default WSL version is 2:
```
wsl --set-default-version 2
```
or if the distro is already installed, check its WSL version:
```
wsl --list --all --verbose
```
and if it is 1, change it to 2:
```
wsl --set-version Ubuntu 2
```

Now you should be able to run Docker on WSL2 inside the VM.

### Errors
These are some of the related error messages I put here to be searchable:

Error when launching the linux distro for the first time:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
```

Error when running `wsl --set-version <distro_name> 2`:
```
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
```

Error when launching Docker Desktop:
```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\username\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install
```

**Comment by TooManyDots** [comment]
Why Is this closed. I followed the documentation ( https://docs.microsoft.com/en-us/windows/wsl/install-win10 ) and I get this error.

**Comment by gclair** [comment]
Quick check via PowerShell cmdlet to see if you have the hardware virtualization enabled - `(gcim Win32_ComputerSystem).HypervisorPresent`

**Comment by hydev777** [comment]
> > Hi @ktmn ,
> > Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after
> > Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> > "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> > C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> > The above resolves the error and got me further. Now...
> > C:>ubunutu.exe
> > Prompts with new username and password.
> > ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)
> 
> thank you thank you

This worked for me.

**Comment by gaoyike** [comment]
C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.

**Comment by RajanikanthGitHub** [comment]
> `$ wsl --set-default-version 1`
> 
> This one solved it for me.
> 
> > Hi @ktmn ,
> > Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after
> > Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> > "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> > C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> > The above resolves the error and got me further. Now...
> > C:>ubunutu.exe
> > Prompts with new username and password.
> > ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)
> 
> This one solved it for me.

This is solved for me as well.
Run below command;
wsl --set-default-version 1

**Comment by jfreeman2** [comment]
I am receiving the mentioned error when attempting to install WSL2.
Windows Version: 20H2
Per comments in this issue/other documentation I have seen, I have taken the following steps:
1.	Enabled Hyper-V
2.	Enabled Virtualization in the BIOS
3.	Disabled "virtual machine platform", restarted my machine, enabled "virtual machine platform" then restarted again

It seems that most in this thread have been able to fix the WSL2 install issue by enabling virtualization in the BIOS.  Virtualization is enabled for me, but I am still running into the same error.  
Any suggestions?

**Comment by jfreeman2** [comment]
> @jfreeman2
> 
> > Any suggestions?
> 
> Confirm in powershell if it can see a hardware Hypervisor
> 
> ```
>     PS cmdlet: (gcim Win32_ComputerSystem).HypervisorPresent
>     False == not enabled.
> ```
> 
> Confirm your version: PowerShell cmdlet : `[environment]::OSVersion.Version`
> WSL 2 is only available in Windows 10, Version 1903, Build 18362, WSL 1 for earlier versions
> 
> And packages/components I used and installed via PowerShell:
> 
> ```
> C:\> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> C:\> dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> C:\> Restart-Computer
> ```
> 
> The install instructions I used for my home and work computer might be helpful - https://github.com/gclair/WSL2_4_nix_nerds#install-wsl2


@gclair thanks for the response!

1. "(gcim Win32_ComputerSystem).HypervisorPresent"
![image](https://user-images.githubusercontent.com/55115751/122955729-f7e33980-d345-11eb-99da-7f5668a59544.png)

The confusing thing is that Hyper-V is enabled in my windows features:
![image](https://user-images.githubusercontent.com/55115751/122957384-81dfd200-d347-11eb-9ac4-999a6305044a.png)

2. [environment]::OSVersion.Version
![image](https://user-images.githubusercontent.com/55115751/122957764-de42f180-d347-11eb-9b23-6c616f8eee80.png)

I have two co-workers that run wsl2 on windows version 20H2/build 19042

3. I ran the specified commands but am still running into the same error. 

4. Great wsl2 install article!  I've gone through your steps/other referenced github issues and hyper v still doesn't seem to be enabled.  In my BIOS there is nothing obviously labeled "virtualization", but I see a field labeled "VMX".  That field is enabled...if my understanding is correct, that field enables virtualization.   

![image](https://user-images.githubusercontent.com/55115751/122959370-aa1c0080-d348-11eb-822e-81766a3f464e.png)

**Comment by gclair** [comment]
@jfreeman2  From a bios perspective that seems right to me, i don't have a modern intel machine to compare it to. 

How do the other components look? You can have WSL running without Hyper-V.

![image](https://user-images.githubusercontent.com/5864402/122995254-c1c2ab80-d37f-11eb-92c1-509efce7efcc.png)

**Comment by jfreeman2** [comment]
@gclair the only thing that looks different about mine is the "Windows Hypervisor Platform".  I have that component checked.  

![image](https://user-images.githubusercontent.com/55115751/122996998-288c9880-d371-11eb-9c85-1ce37ad20cb6.png)

**Comment by gclair** [comment]
@jfreeman2 well  I'm plumb out of ideas, sorry 'bout that! switching to wsl1 is an option but an undesirable one IMO. I look forward to hearing the solution that does work for you, i'd love to update my reference doc with it.

**Comment by jfreeman2** [comment]
@gclair no worries...thanks for your help!  Going to get in touch with someone at Microsoft to see if they can provide a solution.  There's a chance that my specific form of this issue comes from hardware incompatibility, but I have no idea.  I'll send a message out to this thread if I can find a solution.

**Comment by Dalot** [comment]
Tried everything above, one by one, nothing worked for me.

**Comment by udaybais** [comment]
![Screenshot 2021-07-08 090315](https://user-images.githubusercontent.com/55787624/124858284-61607a80-dfcb-11eb-8ad1-0c6db871ee17.png)
firstly ,
>open  windows feature turn on or off.
>turn of the above two.(hypervisor and virtualizations)
>restart device.
>again open and turn on both.
>restart
It worked in my case.
problem happened because i used BLUESTACKS EMULATOR  . emulator is not opening now. emulator of kali
definitely kali is better

**Comment by farshidhss** [comment]
> "The Virtual machine could not be started because a required feature is not installed"
> 
> How about make the message say _which_ feature is not installed.
> 
> I got Virtualization enabled in BIOS, `Windows Subsystems for Linux` and `Virtual Machine Platform` enabled in Windows features, still get the message.
> Do I need `Hyper-V` enabled? Do I need `Windows Hypervisor Platform`?
> 
> Edit: no, enabling these 2 didn't solve it either.
> 
> Edit 2: running `bcdedit /set hypervisorlaunchtype auto start` and reboot seems to have worked for me. So maybe I _did_ need Hyper-V and/or Hypervisor Platform enabled, but it doesn't tell you anything useful.

This is the only thing that worked for me.

**Comment by veekthoven** [comment]
> Hi @ktmn ,
> 
> Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after
> Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> 
> "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> 
> C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> 
> The above resolves the error and got me further. Now...
> 
> C:>ubunutu.exe
> Prompts with new username and password.
> 
> ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)

This works for me too!

**Comment by Bitcents** [comment]
I faced a similar problem today. I used WSL 2 for a long time, but had to disable SVM and Hyper-V as my work required me to use VMWare for some time. The project was finished yesterday and so I decided to reinstall Ubuntu. This is when the 0x80370102 was thrown. I reactivated Hyper-V, but forgot to re-enable SVM; this obviously led to some headache. Re-enabling SVM, however, fixed the problem. Hope this helps.

**Comment by Umisyus** [comment]
@Bitcents Hello, what is "svm"? is it a windows feature or a hardware feature? I'm having this issue as above. wsl2 will not work

WslRegisterDistribution failed with error: **0x80370102**
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
I am believe that I have VT-x Virtualization enabled as Virtualization is showing Enabled in the Task Manager, but there is no option in BIOS for setting that for some reason. Thanks.

**Comment by Umisyus** [comment]
"Secure Virtual Mode"

**Comment by Bitcents** [comment]
> @Bitcents Hello, what is "svm"? is it a windows feature or a hardware feature? I'm having this issue as above. wsl2 will not work
> 
> WslRegisterDistribution failed with error: **0x80370102**
> Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.
> I am believe that I have VT-x Virtualization enabled as Virtualization is showing Enabled in the Task Manager, but there is no option in BIOS for setting that for some reason. Thanks.

Hey Umisyus. SVM is for AMD as VT-X is for Intel. If you have it enabled, then the problem with wsl may be from some of the other reasons mentioned above. Have you checked if the required Windows features are also installed?

**Comment by muradtheOZ** [comment]
> Hi @ktmn ,
> 
> Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> 
> "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> 
> C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> 
> The above resolves the error and got me further. Now...
> 
> C:>ubunutu.exe Prompts with new username and password.
> 
> ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)

Thanks This works for me also

**Comment by Umisyus** [comment]
Realized that I needed to update my system and WSL2 started working after updating Windows.

**Comment by lesniewskii** [comment]
To enable virtualization on AMD u should do this at BOIS
(Advanced → CPU Configuration → SVM → Enable)

**Comment by maysammansoury** [comment]
> > Hi @ktmn ,
> > Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> > "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> > C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> > The above resolves the error and got me further. Now...
> > C:>ubunutu.exe Prompts with new username and password.
> > ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)
> 
> Thanks This works for me also

Thanks bro, It works for me as well

**Comment by datlechin** [comment]
> Hi @ktmn ,
> 
> Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> 
> "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> 
> C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> 
> The above resolves the error and got me further. Now...
> 
> C:>ubunutu.exe Prompts with new username and password.
> 
> ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)

it's works, amazing!!
Thank you

**Comment by piknik1979** [comment]
> Is virtualization enabled in your BIOS? That could be a quick fix.
> 
> We're tracking this issue over in #404 and we can help you troubleshoot there!

Hello ! I'm getting the same problem on my Laptop with Windows 10 - however I'm not sure If I can change the visualisation in BIOS. Can you help with it, thanks!

**Comment by kirannadimpalli** [comment]
For this issue follow these steps 💯 
🔢 🥇 
1) go to windows PowerShell and run as administrator
2) paste this      wsl --set-default-version 1
3) open Ubuntu again and check for error issue is resolved
4) Thanks me later 👍🏻

**Comment by numeralz** [comment]
If anyone else is still struggling with this, and are tired of seeing "Enable virtualization in BIOS" because it's enabled:

For me, there was a `hunter1.sys` driver, which I believe was installed as part of an anti-cheat mechanism from some Steam game I had installed recently.

How I discovered it:  
`Windows Security > Device Security > Memory Integrity > ON`

Gives me some error of a conflicting driver: 
hunter1.sys

I found the `hunter1.sys`, deleted it, rebooted. BINGO. WSL 2 now works as if nothing had ever broke -.-

**Comment by shrujandev** [comment]
> Hi @ktmn ,
> 
> Windows Subsystem for Linux or #WSL is for me and I'm aware this issue was closed. I got the following error after Upgrading #WSL Windows Subsystem for #Linux on Windows 10 Professional with only bios #Virtualization and not SLAT.
> 
> "#0x80370102 the #virtual #machine could not be started because a required feature is not installed."
> 
> C:>wsl --set-default-version 1, Set default version 1, resolves the error on my desktop.
> 
> The above resolves the error and got me further. Now...
> 
> C:>ubunutu.exe Prompts with new username and password.
> 
> ![WSL2_Error_0x80370102](https://user-images.githubusercontent.com/132991/94378978-01ab7980-00f3-11eb-80c9-50b5bc38d2ab.JPG)

This solution worked for me 
For some of the users, the Virtualization is already turned on but still, it gives you an error a simple fix would be to set the wsl version to 1
1: run your powershell in administrator mode 
2: run the command ` wsl --set-default-version 1`
3: try running the linux you installed from windows store

**Comment by arnabbiswas1** [comment]
`$ wsl --set-default-version 1` worked for me. Don't enable Hyper-V unless it's needed, since it has other consequences.

**Comment by bogdan-panteleev** [comment]
why the issue is closed? It is not solved and has must not be closed. Only downgrade to WSL 1 worked for me. Please create good error messages

**Comment by ssbarnea** [comment]
Any hints on how to enable this on Azure machines?

**Comment by Gaurav-8604** [comment]
> Following instructions on https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback with a fairly clean install of Build 18922
> 
> * enabled The VMPlatform, reboot
> * enabled wsl, reboot
> * `wsl set-default-verion 2`
> * Install Ubuntu from store - https://aka.ms/wslstore as directed by `wsl -l -v`
> * Launch Ubuntu
> 
> Get the above error.

wsl --set-default-version 1

This worked for me

**Comment by sonrad10** [comment]
I was getting this error when trying to install Kali. I found this page which fixed it for me:

https://www.kali.org/docs/wsl/win-kex/

The key commands are:

```
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
```

Followed by a restart :)

**Comment by mrx7014** [comment]
`sudo apt update`

**Comment by LukasJerabek** [comment]
On vmware windows virtual machine I had to go to setting of virtual machine, click on processors and enable Virtualize Intel VT-x/EPT or AMD-V/RVI. After that I could check hyperV in windows features (that were greyed out before). Reboot and than I got rid of the anoying error.

**Comment by QuinntonCarter** [comment]
> I had a similar problem on when installing on my new system. I checked my BIOS @craigloewen-msft as mentioned. The first time I didn't find anything but after doing a bit more research I tried turning on SVM in the BIOS and it worked. (I also turned on the Windows Hypervisor setting in Windows Features)
> 
> (Advanced → CPU Configuration → SVM → Enable)
> 
> This is the case for AMD systems. Apparently it is different for Intel based systems.

This worked for me, I run an AMD CPU. Thank you

**Comment by NeonWizard** [comment]
Still the same issue 4 years later.

- SVM enabled
- Virtualization enabled
- HyperV installed
- Virtual Machine Platform installed
- Windows Hypervisor Platform installed
- Windows Subsystem for Linux installed
- Windows updated
- `wsl.exe --install --no-distribution`
- `bcdedit /set hypervisorlaunchtype auto start`
- Many reboots

Nothing has worked. This started happening a couple days after I killed a docker backend process because it was memory leaking really bad (20+ GB). Next time I restarted, WSL started giving this error.

**Comment by MichalGrzegorzak** [comment]
> Nothing has worked. This started happening a couple days after I killed a docker backend process because it was memory leaking really bad (20+ GB). Next time I restarted, WSL started giving this error.

Exactly the same story as @NeonWizard described, had the same memory leak. No Docker for me ever since :/

**Comment by JacobDrivers** [comment]
> `wsl --set-default-version 1` Worked for me. Had this issue. I previously had tried out WSL2, disabled the feature/uninstalled, and wanted to have WSL again, but without enabling hypervisor (Which is required for WSL2) because I use VMware a lot. I guess it had remembered me setting the default to WSL2. So, the fix for me was `wsl --set-default-version 1`.
> 
> They need to add WHY to the error. It would be simple to code in what requirement is missing, or if WSL is set differently. Would help a lot! Thanks.

@MichalGrzegorzak @NeonWizard 
Did you both try this at all? (From my previous comment above) Forgive me if you have, or don't need to. You could also try `wsl --update` just to be sure you are on the latest WSL.

You could also do `wsl -l -v` and see what exact distros you have, what is going on, etc.

Let me know if anything works.
